name: ğŸ”§ Build ğŸ“º slides and ğŸ§® demos, and ğŸš€ deploy them to GitHub Pages
on: push
jobs:
  build-n-deploy:
    name: Build and deploy
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
    - name: Checkout code ğŸ›ï¸
      uses: actions/checkout@v3
      with:
        persist-credentials: false
    - name: Install Test
      run: |
          pip install git+https://git@github.com/xmlx-io/xml-book-code.git@turing-release
    - name: Set up SSH keys ğŸ”‘
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: |
          ${{ secrets.XML_BOOK_CODE_DEPLOY_KEY }}
    - name: Cache builds, models and data
      uses: actions/cache@v3
      with:
        path: |
          /home/runner/.cache/torch
        key: ${{ runner.os }}-data_models
    - name: Set up Python 3.9 ğŸ
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
        cache: 'pip'
    - name: Install LaTeX
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          dvipng \
          texlive \
          texlive-xetex \
          texlive-fonts-recommended \
          cm-super
    - name: Install Quarto ğŸ’¾
      run: |
        wget -O quarto.deb https://github.com/quarto-dev/quarto-cli/releases/download/v1.2.313/quarto-1.2.313-linux-amd64.deb
        QUARTO_INSTALLER=$(readlink -f quarto.deb)
        sudo dpkg -i "$QUARTO_INSTALLER"
        sudo apt-get install -f
    - name: Install Quarto and Python dependencies ğŸ’¾
      run: |
        pip install -r requirements.txt
        quarto install extension --no-prompt quarto-ext/fontawesome
    - name: Get PyTorch model
      run: |
        python -c 'import torchvision.models as models; models.inception_v3(pretrained=True);'
        python -c 'import torchvision.models as models; models.alexnet(pretrained=True);'
    - name: ğŸ”§ Build Jupyter Notebooks ğŸ§® (demos)
      run: make build-demos
    - name: ğŸ”§ Build Quarto Slides ğŸ“º (slides)
      run: make build-slides
    - name: Add web README.md
      run: cp slides/_web_readme.md _build/README.md
    - name: Deploy (Custom Domain) ğŸš€
      if: github.ref == 'refs/heads/master'
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.CONCIERGE_ACCESS_TOKEN }}
        REPOSITORY_NAME: xmlx-io/usi-slides
        BRANCH: webpage
        FOLDER: _build
        CLEAN: true
    - name: Deploy Preparation (Mirror) ğŸ”§
      run: rm _build/CNAME
    - name: Deploy (Mirror) ğŸš€
      if: github.ref == 'refs/heads/master'
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.CONCIERGE_ACCESS_TOKEN }}
        REPOSITORY_NAME: xmlx-io/usi-slides-mirror
        BRANCH: webpage
        FOLDER: _build
        CLEAN: true
